### ISSUE TITLE
Prevent command injection

### ISSUE THREAD

**Issue by domodwyer** [oss6/statico-frontend#1]
Hey Oss!

I like what you're doing! I saw a bug you should know about though.
Get the site up and running and register an account with your name as:

```
;echo "Hi from <?php echo 'Dom' ?>" > /var/www/statico-frontend/public/test.php;#
```

To get the 'new site' page working I had to change `public/js/site.js` like so:

``` javascript
var newSite = function () {
            return {
                author: 'Dom', //user.name,
                url: 'http://example.com',
                root_url: '/',
                paginate: 10,
                github_repo_count: 5
            };
        };
```

Then create a new site and go to `statico-frontend.dev/test.php`!

I'd suggest validating the username with some regex (i.e. alpha-numeric only) when creating the account to prevent any dodgy usernames **and** using `escapeshellcmd() / escapeshellarg()` any time you do `exec()` or the like.

Let me know if you need any help, nice to see a bit of angular!

**Comment by oss6** [comment]
Hi Dom!!

Thank you for raising this issue! I will look into that as soon as possible.
I should be paying more attention to these issues :+1:
